CREATE DATABASE customer_behavior;

SELECT name
FROM sys.databases;

USE customer_behavior;
GO
SELECT TOP 5 *
FROM customer;


--Q1. What is the total revenue generated by Male vs Female customers?

select gender,
sum(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount) from customer)


--Q3. Which are the top 5 products with the highest average review rating?
select top 5
	item_purchased,
	avg(review_rating) As average_review_rating
from customer
group by item_purchased
order by average_review_rating desc;


--Q4. Compare the average purchase amounts between standard and express shipping.
SELECT
    shipping_type,
    AVG(purchase_amount) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers.
SELECT
    subscription_status,
    AVG(purchase_amount) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE
            WHEN discount_applied = 'Yes' THEN 1
            ELSE 0
        END) AS discounted_purchases,
    ROUND(
        100.0 * SUM(CASE
                        WHEN discount_applied = 'Yes' THEN 1
                        ELSE 0
                    END) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

--Q7. Segment customers into new, returning and loyal based on their total umber of previous purchases, and show the count of each segment.
SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM
(
    SELECT
        CASE
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS customer_segments
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category?
WITH ProductSales AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),
RankedProducts AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS rank_no
    FROM ProductSales
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM RankedProducts
WHERE rank_no <= 3
ORDER BY category, rank_no;

--Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10, What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

